[2024-07-02T10:41:35.858-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T10:41:35.876-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.consume_kafka_movie_details scheduled__2024-07-01T00:01:15+00:00 [queued]>
[2024-07-02T10:41:35.887-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.consume_kafka_movie_details scheduled__2024-07-01T00:01:15+00:00 [queued]>
[2024-07-02T10:41:35.887-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-02T10:41:35.919-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): consume_kafka_movie_details> on 2024-07-01 00:01:15+00:00
[2024-07-02T10:41:35.924-0400] {standard_task_runner.py:63} INFO - Started process 498041 to run task
[2024-07-02T10:41:35.926-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'consume_kafka_movie_details', 'scheduled__2024-07-01T00:01:15+00:00', '--job-id', '1179', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmppxseiqll']
[2024-07-02T10:41:35.928-0400] {standard_task_runner.py:91} INFO - Job 1179: Subtask consume_kafka_movie_details
[2024-07-02T10:41:36.005-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.consume_kafka_movie_details scheduled__2024-07-01T00:01:15+00:00 [running]> on host walter-VirtualBox
[2024-07-02T10:41:36.124-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='consume_kafka_movie_details' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:01:15+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:01:15+00:00'
[2024-07-02T10:41:36.126-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T10:41:38.151-0400] {logging_mixin.py:188} INFO - No se recibieron m치s mensajes, terminando la ejecuci칩n.
[2024-07-02T10:41:38.158-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T10:41:38.158-0400] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/airflow/dags/movie_recommend.py", line 87, in consume_kafka_movie_details
    ti.xcom_push(key='json_data_movie', value=json_all_details)
                                              ^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'json_all_details' where it is not associated with a value
[2024-07-02T10:41:38.165-0400] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=api_cuevana3_movie, task_id=consume_kafka_movie_details, run_id=scheduled__2024-07-01T00:01:15+00:00, execution_date=20240701T000115, start_date=20240702T144135, end_date=20240702T144138
[2024-07-02T10:41:38.191-0400] {standard_task_runner.py:110} ERROR - Failed to execute job 1179 for task consume_kafka_movie_details (cannot access local variable 'json_all_details' where it is not associated with a value; 498041)
[2024-07-02T10:41:38.216-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T10:41:38.226-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T10:41:38.227-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-02T10:58:23.992-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T10:58:24.014-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.consume_kafka_movie_details scheduled__2024-07-01T00:01:15+00:00 [queued]>
[2024-07-02T10:58:24.019-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.consume_kafka_movie_details scheduled__2024-07-01T00:01:15+00:00 [queued]>
[2024-07-02T10:58:24.019-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-02T10:58:24.041-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): consume_kafka_movie_details> on 2024-07-01 00:01:15+00:00
[2024-07-02T10:58:24.048-0400] {standard_task_runner.py:63} INFO - Started process 501186 to run task
[2024-07-02T10:58:24.051-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'consume_kafka_movie_details', 'scheduled__2024-07-01T00:01:15+00:00', '--job-id', '1337', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmpb025w3zg']
[2024-07-02T10:58:24.053-0400] {standard_task_runner.py:91} INFO - Job 1337: Subtask consume_kafka_movie_details
[2024-07-02T10:58:24.108-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.consume_kafka_movie_details scheduled__2024-07-01T00:01:15+00:00 [running]> on host walter-VirtualBox
[2024-07-02T10:58:24.195-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='consume_kafka_movie_details' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:01:15+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:01:15+00:00'
[2024-07-02T10:58:24.196-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T10:58:26.452-0400] {logging_mixin.py:188} INFO - No se recibieron m치s mensajes, terminando la ejecuci칩n.
[2024-07-02T10:58:26.463-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T10:58:26.464-0400] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/airflow/dags/movie_recommend.py", line 87, in consume_kafka_movie_details
    ti.xcom_push(key='json_data_movie', value=json_all_details)
                                              ^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'json_all_details' where it is not associated with a value
[2024-07-02T10:58:26.474-0400] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=api_cuevana3_movie, task_id=consume_kafka_movie_details, run_id=scheduled__2024-07-01T00:01:15+00:00, execution_date=20240701T000115, start_date=20240702T145824, end_date=20240702T145826
[2024-07-02T10:58:26.495-0400] {standard_task_runner.py:110} ERROR - Failed to execute job 1337 for task consume_kafka_movie_details (cannot access local variable 'json_all_details' where it is not associated with a value; 501186)
[2024-07-02T10:58:26.516-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T10:58:26.554-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T10:58:26.555-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
