[2024-07-01T20:02:32.823-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-01T20:02:32.836-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.execute_post_details_fasapi scheduled__2024-07-01T06:00:00+00:00 [queued]>
[2024-07-01T20:02:32.842-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.execute_post_details_fasapi scheduled__2024-07-01T06:00:00+00:00 [queued]>
[2024-07-01T20:02:32.842-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-01T20:02:32.883-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): execute_post_details_fasapi> on 2024-07-01 06:00:00+00:00
[2024-07-01T20:02:32.890-0400] {standard_task_runner.py:63} INFO - Started process 412797 to run task
[2024-07-01T20:02:32.892-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'execute_post_details_fasapi', 'scheduled__2024-07-01T06:00:00+00:00', '--job-id', '707', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmp2w1o0m28']
[2024-07-01T20:02:32.894-0400] {standard_task_runner.py:91} INFO - Job 707: Subtask execute_post_details_fasapi
[2024-07-01T20:02:32.991-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.execute_post_details_fasapi scheduled__2024-07-01T06:00:00+00:00 [running]> on host walter-VirtualBox
[2024-07-01T20:02:33.081-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='execute_post_details_fasapi' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T06:00:00+00:00'
[2024-07-01T20:02:33.082-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-01T20:06:39.502-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-01T20:06:39.503-0400] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/walter/Documentos/rakuntentv/airflow/dags/movie_recommend.py", line 58, in execute_post_details_fasapi
    response = requests.post(api_url)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/airflow/dags/movie_recommend.py", line 83, in execute_post_details_fasapi
    consumer.close()
    ^^^^^^^^
UnboundLocalError: cannot access local variable 'consumer' where it is not associated with a value
[2024-07-01T20:06:39.569-0400] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=api_cuevana3_movie, task_id=execute_post_details_fasapi, run_id=scheduled__2024-07-01T06:00:00+00:00, execution_date=20240701T060000, start_date=20240702T000232, end_date=20240702T000639
[2024-07-01T20:06:39.608-0400] {standard_task_runner.py:110} ERROR - Failed to execute job 707 for task execute_post_details_fasapi (cannot access local variable 'consumer' where it is not associated with a value; 412797)
[2024-07-01T20:06:39.657-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-01T20:06:39.671-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-01T20:06:39.708-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-01T23:10:17.584-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-01T23:10:17.597-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.execute_post_details_fasapi scheduled__2024-07-01T06:00:00+00:00 [queued]>
[2024-07-01T23:10:17.601-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.execute_post_details_fasapi scheduled__2024-07-01T06:00:00+00:00 [queued]>
[2024-07-01T23:10:17.601-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-01T23:10:17.617-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): execute_post_details_fasapi> on 2024-07-01 06:00:00+00:00
[2024-07-01T23:10:17.622-0400] {standard_task_runner.py:63} INFO - Started process 446788 to run task
[2024-07-01T23:10:17.624-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'execute_post_details_fasapi', 'scheduled__2024-07-01T06:00:00+00:00', '--job-id', '832', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmps2i8x0au']
[2024-07-01T23:10:17.626-0400] {standard_task_runner.py:91} INFO - Job 832: Subtask execute_post_details_fasapi
[2024-07-01T23:10:17.654-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.execute_post_details_fasapi scheduled__2024-07-01T06:00:00+00:00 [running]> on host walter-VirtualBox
[2024-07-01T23:10:17.728-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='execute_post_details_fasapi' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T06:00:00+00:00'
[2024-07-01T23:10:17.729-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-01T23:11:10.371-0400] {logging_mixin.py:188} INFO - Scraping movie details running successfully
[2024-07-01T23:11:10.402-0400] {logging_mixin.py:188} INFO - {"image_url": "https://i0.wp.com/www.themoviedb.org/t/p/w185/Adh7xmtgSIUGZBaMj9VLTmq2G8z.jpg", "title": "Tarot", "rating": 6.6, "duration": "1h 32m", "year": "2024", "quality": "HD", "description": "Ver tarot Cuevana3.Un grupo de amigos de la universidad comienzan a morir de maneras relacionadas con su fortuna despu\u00e9s de que les lean los hor\u00f3scopos.", "genre": ["Terror"], "country": "United States", "director": "Spenser Cohen", "actors": ["Harriet Slater,", "Adain Bradley,", "Avantika,", "Jacob Batalon,", "Humberly Gonz\u00e1lez,", "Wolfgang Novogratz,", "Larsen Thompson,", "Olwen Fou\u00e9r\u00e9,", "Sun\u010dica Milanovi\u0107,", "Alan Wells,", "Joss Carter,", "James Swanton,", "Sta\u0161a Nikoli\u0107,", "Anna Halberg,", "Cavin Cornwall,", "Lucy Ridley,", "Felix Leech,", "Vahidin Preli\u0107,", "Dunja Pavlovi\u0107,", "Vi\u0161nja Obradovi\u0107,"], "views": 612}
[2024-07-01T23:11:10.427-0400] {python.py:237} INFO - Done. Returned value was: {"image_url": "https://i0.wp.com/www.themoviedb.org/t/p/w185/Adh7xmtgSIUGZBaMj9VLTmq2G8z.jpg", "title": "Tarot", "rating": 6.6, "duration": "1h 32m", "year": "2024", "quality": "HD", "description": "Ver tarot Cuevana3.Un grupo de amigos de la universidad comienzan a morir de maneras relacionadas con su fortuna despu\u00e9s de que les lean los hor\u00f3scopos.", "genre": ["Terror"], "country": "United States", "director": "Spenser Cohen", "actors": ["Harriet Slater,", "Adain Bradley,", "Avantika,", "Jacob Batalon,", "Humberly Gonz\u00e1lez,", "Wolfgang Novogratz,", "Larsen Thompson,", "Olwen Fou\u00e9r\u00e9,", "Sun\u010dica Milanovi\u0107,", "Alan Wells,", "Joss Carter,", "James Swanton,", "Sta\u0161a Nikoli\u0107,", "Anna Halberg,", "Cavin Cornwall,", "Lucy Ridley,", "Felix Leech,", "Vahidin Preli\u0107,", "Dunja Pavlovi\u0107,", "Vi\u0161nja Obradovi\u0107,"], "views": 612}
[2024-07-01T23:11:10.432-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-01T23:11:10.467-0400] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=api_cuevana3_movie, task_id=execute_post_details_fasapi, run_id=scheduled__2024-07-01T06:00:00+00:00, execution_date=20240701T060000, start_date=20240702T031017, end_date=20240702T031110
[2024-07-01T23:11:10.526-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-01T23:11:10.543-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-01T23:11:10.545-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
