[2024-06-27T22:24:48.713-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:24:48.800-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-06-27T22:24:48.825-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-06-27T22:24:48.826-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-27T22:24:48.892-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_into_mysql> on 2024-06-27 00:00:00+00:00
[2024-06-27T22:24:48.899-0400] {standard_task_runner.py:63} INFO - Started process 226122 to run task
[2024-06-27T22:24:48.903-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'insert_into_mysql', 'scheduled__2024-06-27T00:00:00+00:00', '--job-id', '365', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmpmp5qmoon']
[2024-06-27T22:24:48.905-0400] {standard_task_runner.py:91} INFO - Job 365: Subtask insert_into_mysql
[2024-06-27T22:24:48.993-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [running]> on host walter-VirtualBox
[2024-06-27T22:24:49.283-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='insert_into_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:00:00+00:00'
[2024-06-27T22:24:49.284-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:24:50.431-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:24:50.432-0400] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/airflow/dags/movie_recommend.py", line 122, in insert_into_mysql
    actors = json_data['actor']
             ~~~~~~~~~^^^^^^^^^
KeyError: 'actor'
[2024-06-27T22:24:50.448-0400] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=api_cuevana3_movie, task_id=insert_into_mysql, run_id=scheduled__2024-06-27T00:00:00+00:00, execution_date=20240627T000000, start_date=20240628T022448, end_date=20240628T022450
[2024-06-27T22:24:50.481-0400] {standard_task_runner.py:110} ERROR - Failed to execute job 365 for task insert_into_mysql ('actor'; 226122)
[2024-06-27T22:24:50.512-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-27T22:24:50.535-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:24:50.537-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T09:51:36.404-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T09:51:36.421-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-06-28T09:51:36.430-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-06-28T09:51:36.431-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T09:51:36.466-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_into_mysql> on 2024-06-27 00:00:00+00:00
[2024-06-28T09:51:36.475-0400] {standard_task_runner.py:63} INFO - Started process 229775 to run task
[2024-06-28T09:51:36.479-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'insert_into_mysql', 'scheduled__2024-06-27T00:00:00+00:00', '--job-id', '385', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmpknd78r_f']
[2024-06-28T09:51:36.481-0400] {standard_task_runner.py:91} INFO - Job 385: Subtask insert_into_mysql
[2024-06-28T09:51:36.563-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [running]> on host walter-VirtualBox
[2024-06-28T09:51:36.703-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='insert_into_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:00:00+00:00'
[2024-06-28T09:51:36.709-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T09:51:36.830-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T09:51:36.831-0400] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/airflow/dags/movie_recommend.py", line 133, in insert_into_mysql
    cursor.execute(insert_query,(title,years,quality,duration,rating,descriptions,genre,
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 359, in execute
    prepared = self._cnx.prepare_for_mysql(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 866, in prepare_for_mysql
    result = self._cmysql.convert_to_mysql(*params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_mysql_connector.MySQLInterfaceError: Python type list cannot be converted
[2024-06-28T09:51:36.845-0400] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=api_cuevana3_movie, task_id=insert_into_mysql, run_id=scheduled__2024-06-27T00:00:00+00:00, execution_date=20240627T000000, start_date=20240628T135136, end_date=20240628T135136
[2024-06-28T09:51:36.883-0400] {standard_task_runner.py:110} ERROR - Failed to execute job 385 for task insert_into_mysql (Python type list cannot be converted; 229775)
[2024-06-28T09:51:36.918-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T09:51:36.968-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T09:51:36.970-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T10:48:14.245-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T10:48:14.263-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-06-28T10:48:14.270-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-06-28T10:48:14.270-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T10:48:14.324-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_into_mysql> on 2024-06-27 00:00:00+00:00
[2024-06-28T10:48:14.336-0400] {standard_task_runner.py:63} INFO - Started process 235507 to run task
[2024-06-28T10:48:14.341-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'insert_into_mysql', 'scheduled__2024-06-27T00:00:00+00:00', '--job-id', '435', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmpqacxbjod']
[2024-06-28T10:48:14.345-0400] {standard_task_runner.py:91} INFO - Job 435: Subtask insert_into_mysql
[2024-06-28T10:48:14.456-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [running]> on host walter-VirtualBox
[2024-06-28T10:48:14.695-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='insert_into_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:00:00+00:00'
[2024-06-28T10:48:14.698-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T10:48:14.955-0400] {logging_mixin.py:188} INFO - Error al insertar en MySQL: 1364 (HY000): Field 'id' doesn't have a default value
[2024-06-28T10:48:14.959-0400] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T10:48:14.961-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T10:48:14.972-0400] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=api_cuevana3_movie, task_id=insert_into_mysql, run_id=scheduled__2024-06-27T00:00:00+00:00, execution_date=20240627T000000, start_date=20240628T144814, end_date=20240628T144814
[2024-06-28T10:48:15.066-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T10:48:15.090-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T10:48:15.093-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T11:15:45.646-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T11:15:45.699-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-06-28T11:15:45.709-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-06-28T11:15:45.712-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T11:15:45.792-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_into_mysql> on 2024-06-27 00:00:00+00:00
[2024-06-28T11:15:45.818-0400] {standard_task_runner.py:63} INFO - Started process 240926 to run task
[2024-06-28T11:15:45.841-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'insert_into_mysql', 'scheduled__2024-06-27T00:00:00+00:00', '--job-id', '515', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmp4w4s3rck']
[2024-06-28T11:15:45.844-0400] {standard_task_runner.py:91} INFO - Job 515: Subtask insert_into_mysql
[2024-06-28T11:15:45.995-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [running]> on host walter-VirtualBox
[2024-06-28T11:15:46.117-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='insert_into_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:00:00+00:00'
[2024-06-28T11:15:46.117-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T11:15:46.355-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T11:15:46.356-0400] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/airflow/dags/movie_recommend.py", line 115, in insert_into_mysql
    title = movie['title']
            ~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-06-28T11:15:46.364-0400] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=api_cuevana3_movie, task_id=insert_into_mysql, run_id=scheduled__2024-06-27T00:00:00+00:00, execution_date=20240627T000000, start_date=20240628T151545, end_date=20240628T151546
[2024-06-28T11:15:46.407-0400] {standard_task_runner.py:110} ERROR - Failed to execute job 515 for task insert_into_mysql (string indices must be integers, not 'str'; 240926)
[2024-06-28T11:15:46.439-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T11:15:46.467-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T11:15:46.468-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T15:58:56.244-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T15:58:56.266-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-06-28T15:58:56.279-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-06-28T15:58:56.280-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T15:58:56.320-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_into_mysql> on 2024-06-27 00:00:00+00:00
[2024-06-28T15:58:56.328-0400] {standard_task_runner.py:63} INFO - Started process 245043 to run task
[2024-06-28T15:58:56.336-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'insert_into_mysql', 'scheduled__2024-06-27T00:00:00+00:00', '--job-id', '565', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmpdy4ykykf']
[2024-06-28T15:58:56.342-0400] {standard_task_runner.py:91} INFO - Job 565: Subtask insert_into_mysql
[2024-06-28T15:58:56.445-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [running]> on host walter-VirtualBox
[2024-06-28T15:58:56.646-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='insert_into_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:00:00+00:00'
[2024-06-28T15:58:56.647-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T15:58:56.862-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T15:58:56.863-0400] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/airflow/dags/movie_recommend.py", line 115, in insert_into_mysql
    title = movie['title']
            ~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-06-28T15:58:56.873-0400] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=api_cuevana3_movie, task_id=insert_into_mysql, run_id=scheduled__2024-06-27T00:00:00+00:00, execution_date=20240627T000000, start_date=20240628T195856, end_date=20240628T195856
[2024-06-28T15:58:56.897-0400] {standard_task_runner.py:110} ERROR - Failed to execute job 565 for task insert_into_mysql (string indices must be integers, not 'str'; 245043)
[2024-06-28T15:58:56.918-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T15:58:56.945-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T15:58:56.946-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T16:18:03.792-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T16:18:03.823-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-06-28T16:18:03.837-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-06-28T16:18:03.838-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T16:18:03.882-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_into_mysql> on 2024-06-27 00:00:00+00:00
[2024-06-28T16:18:03.894-0400] {standard_task_runner.py:63} INFO - Started process 247740 to run task
[2024-06-28T16:18:03.900-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'insert_into_mysql', 'scheduled__2024-06-27T00:00:00+00:00', '--job-id', '590', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmpcmt_90r6']
[2024-06-28T16:18:03.902-0400] {standard_task_runner.py:91} INFO - Job 590: Subtask insert_into_mysql
[2024-06-28T16:18:03.971-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [running]> on host walter-VirtualBox
[2024-06-28T16:18:04.103-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='insert_into_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:00:00+00:00'
[2024-06-28T16:18:04.105-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T16:18:04.327-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T16:18:04.331-0400] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/airflow/dags/movie_recommend.py", line 119, in insert_into_mysql
    title = movie['title']
            ~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-06-28T16:18:04.344-0400] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=api_cuevana3_movie, task_id=insert_into_mysql, run_id=scheduled__2024-06-27T00:00:00+00:00, execution_date=20240627T000000, start_date=20240628T201803, end_date=20240628T201804
[2024-06-28T16:18:04.379-0400] {standard_task_runner.py:110} ERROR - Failed to execute job 590 for task insert_into_mysql (string indices must be integers, not 'str'; 247740)
[2024-06-28T16:18:04.425-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T16:18:04.451-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T16:18:04.453-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T16:29:58.492-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T16:29:58.541-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-06-28T16:29:58.553-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-06-28T16:29:58.553-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T16:29:58.671-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_into_mysql> on 2024-06-27 00:00:00+00:00
[2024-06-28T16:29:58.693-0400] {standard_task_runner.py:63} INFO - Started process 249937 to run task
[2024-06-28T16:29:58.706-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'insert_into_mysql', 'scheduled__2024-06-27T00:00:00+00:00', '--job-id', '615', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmpoyytadit']
[2024-06-28T16:29:58.723-0400] {standard_task_runner.py:91} INFO - Job 615: Subtask insert_into_mysql
[2024-06-28T16:29:59.002-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:00:00+00:00 [running]> on host walter-VirtualBox
[2024-06-28T16:29:59.233-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='insert_into_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:00:00+00:00'
[2024-06-28T16:29:59.234-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T16:30:02.733-0400] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T16:30:02.735-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T16:30:02.742-0400] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=api_cuevana3_movie, task_id=insert_into_mysql, run_id=scheduled__2024-06-27T00:00:00+00:00, execution_date=20240627T000000, start_date=20240628T202958, end_date=20240628T203002
[2024-06-28T16:30:02.813-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T16:30:02.834-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T16:30:02.835-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
