[2024-06-28T09:52:51.866-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T09:52:51.898-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:00+00:00 [queued]>
[2024-06-28T09:52:51.903-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:00+00:00 [queued]>
[2024-06-28T09:52:51.905-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T09:52:51.935-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_into_mysql> on 2024-06-27 00:01:00+00:00
[2024-06-28T09:52:51.950-0400] {standard_task_runner.py:63} INFO - Started process 230375 to run task
[2024-06-28T09:52:51.953-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'insert_into_mysql', 'scheduled__2024-06-27T00:01:00+00:00', '--job-id', '395', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmpkfa4uwn7']
[2024-06-28T09:52:51.957-0400] {standard_task_runner.py:91} INFO - Job 395: Subtask insert_into_mysql
[2024-06-28T09:52:52.074-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:00+00:00 [running]> on host walter-VirtualBox
[2024-06-28T09:52:52.278-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='insert_into_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:01:00+00:00'
[2024-06-28T09:52:52.281-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T09:52:52.396-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T09:52:52.397-0400] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/airflow/dags/movie_recommend.py", line 133, in insert_into_mysql
    cursor.execute(insert_query,(title,years,quality,duration,rating,descriptions,genre,
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 359, in execute
    prepared = self._cnx.prepare_for_mysql(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 866, in prepare_for_mysql
    result = self._cmysql.convert_to_mysql(*params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_mysql_connector.MySQLInterfaceError: Python type list cannot be converted
[2024-06-28T09:52:52.403-0400] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=api_cuevana3_movie, task_id=insert_into_mysql, run_id=scheduled__2024-06-27T00:01:00+00:00, execution_date=20240627T000100, start_date=20240628T135251, end_date=20240628T135252
[2024-06-28T09:52:52.441-0400] {standard_task_runner.py:110} ERROR - Failed to execute job 395 for task insert_into_mysql (Python type list cannot be converted; 230375)
[2024-06-28T09:52:52.485-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T09:52:52.531-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T09:52:52.533-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T11:02:14.742-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T11:02:14.770-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:00+00:00 [queued]>
[2024-06-28T11:02:14.792-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:00+00:00 [queued]>
[2024-06-28T11:02:14.793-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T11:02:14.822-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_into_mysql> on 2024-06-27 00:01:00+00:00
[2024-06-28T11:02:14.834-0400] {standard_task_runner.py:63} INFO - Started process 237078 to run task
[2024-06-28T11:02:14.842-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'insert_into_mysql', 'scheduled__2024-06-27T00:01:00+00:00', '--job-id', '455', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmpoqg2yh0d']
[2024-06-28T11:02:14.848-0400] {standard_task_runner.py:91} INFO - Job 455: Subtask insert_into_mysql
[2024-06-28T11:02:14.977-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:00+00:00 [running]> on host walter-VirtualBox
[2024-06-28T11:02:15.151-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='insert_into_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:01:00+00:00'
[2024-06-28T11:02:15.152-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T11:02:15.575-0400] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T11:02:15.583-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T11:02:15.595-0400] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=api_cuevana3_movie, task_id=insert_into_mysql, run_id=scheduled__2024-06-27T00:01:00+00:00, execution_date=20240627T000100, start_date=20240628T150214, end_date=20240628T150215
[2024-06-28T11:02:15.665-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T11:02:15.678-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T11:02:15.679-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T11:17:30.813-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T11:17:30.858-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:00+00:00 [queued]>
[2024-06-28T11:17:30.873-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:00+00:00 [queued]>
[2024-06-28T11:17:30.879-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T11:17:30.977-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_into_mysql> on 2024-06-27 00:01:00+00:00
[2024-06-28T11:17:31.012-0400] {standard_task_runner.py:63} INFO - Started process 241544 to run task
[2024-06-28T11:17:31.012-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'insert_into_mysql', 'scheduled__2024-06-27T00:01:00+00:00', '--job-id', '525', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmp7ksbw9s2']
[2024-06-28T11:17:31.014-0400] {standard_task_runner.py:91} INFO - Job 525: Subtask insert_into_mysql
[2024-06-28T11:17:31.227-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:00+00:00 [running]> on host walter-VirtualBox
[2024-06-28T11:17:31.430-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='insert_into_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:01:00+00:00'
[2024-06-28T11:17:31.435-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T11:17:31.645-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T11:17:31.647-0400] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/airflow/dags/movie_recommend.py", line 115, in insert_into_mysql
    title = movie['title']
            ~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-06-28T11:17:31.669-0400] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=api_cuevana3_movie, task_id=insert_into_mysql, run_id=scheduled__2024-06-27T00:01:00+00:00, execution_date=20240627T000100, start_date=20240628T151730, end_date=20240628T151731
[2024-06-28T11:17:31.745-0400] {standard_task_runner.py:110} ERROR - Failed to execute job 525 for task insert_into_mysql (string indices must be integers, not 'str'; 241544)
[2024-06-28T11:17:31.777-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T11:17:31.858-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T11:17:31.861-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T16:00:13.401-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T16:00:13.416-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:00+00:00 [queued]>
[2024-06-28T16:00:13.422-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:00+00:00 [queued]>
[2024-06-28T16:00:13.423-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T16:00:13.437-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_into_mysql> on 2024-06-27 00:01:00+00:00
[2024-06-28T16:00:13.443-0400] {standard_task_runner.py:63} INFO - Started process 245653 to run task
[2024-06-28T16:00:13.445-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'insert_into_mysql', 'scheduled__2024-06-27T00:01:00+00:00', '--job-id', '575', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmpbvdww0j1']
[2024-06-28T16:00:13.447-0400] {standard_task_runner.py:91} INFO - Job 575: Subtask insert_into_mysql
[2024-06-28T16:00:13.529-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:00+00:00 [running]> on host walter-VirtualBox
[2024-06-28T16:00:13.599-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='insert_into_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:01:00+00:00'
[2024-06-28T16:00:13.600-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T16:00:13.656-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T16:00:13.657-0400] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/airflow/dags/movie_recommend.py", line 115, in insert_into_mysql
    title = movie['title']
            ~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-06-28T16:00:13.668-0400] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=api_cuevana3_movie, task_id=insert_into_mysql, run_id=scheduled__2024-06-27T00:01:00+00:00, execution_date=20240627T000100, start_date=20240628T200013, end_date=20240628T200013
[2024-06-28T16:00:13.710-0400] {standard_task_runner.py:110} ERROR - Failed to execute job 575 for task insert_into_mysql (string indices must be integers, not 'str'; 245653)
[2024-06-28T16:00:13.724-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T16:00:13.749-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T16:00:13.750-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T16:19:40.610-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T16:19:40.634-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:00+00:00 [queued]>
[2024-06-28T16:19:40.639-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:00+00:00 [queued]>
[2024-06-28T16:19:40.640-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T16:19:40.655-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_into_mysql> on 2024-06-27 00:01:00+00:00
[2024-06-28T16:19:40.660-0400] {standard_task_runner.py:63} INFO - Started process 248347 to run task
[2024-06-28T16:19:40.666-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'api_cuevana3_movie', 'insert_into_mysql', 'scheduled__2024-06-27T00:01:00+00:00', '--job-id', '600', '--raw', '--subdir', 'DAGS_FOLDER/movie_recommend.py', '--cfg-path', '/tmp/tmp5wz8f94c']
[2024-06-28T16:19:40.667-0400] {standard_task_runner.py:91} INFO - Job 600: Subtask insert_into_mysql
[2024-06-28T16:19:40.741-0400] {task_command.py:426} INFO - Running <TaskInstance: api_cuevana3_movie.insert_into_mysql scheduled__2024-06-27T00:01:00+00:00 [running]> on host walter-VirtualBox
[2024-06-28T16:19:40.841-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_cuevana3_movie' AIRFLOW_CTX_TASK_ID='insert_into_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:01:00+00:00'
[2024-06-28T16:19:40.842-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T16:19:41.000-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T16:19:41.002-0400] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walter/Documentos/rakuntentv/airflow/dags/movie_recommend.py", line 119, in insert_into_mysql
    title = movie['title']
            ~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-06-28T16:19:41.019-0400] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=api_cuevana3_movie, task_id=insert_into_mysql, run_id=scheduled__2024-06-27T00:01:00+00:00, execution_date=20240627T000100, start_date=20240628T201940, end_date=20240628T201941
[2024-06-28T16:19:41.048-0400] {standard_task_runner.py:110} ERROR - Failed to execute job 600 for task insert_into_mysql (string indices must be integers, not 'str'; 248347)
[2024-06-28T16:19:41.095-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T16:19:41.108-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T16:19:41.109-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
